name: AVEST CICD DEV

on:
  push:
    branches:
      - development
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - reopened
      - edited
    branches: "development"

env:
  TARGET_PR_LABEL: "deploy_to_dev"

jobs:
  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/development') || 
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, '${TARGET_PR_LABEL}'))

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
