name: AVEST CICD DEV

on:
  push:
    branches:
      - development
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
    branches: "development"

env:
  TARGET_PR_LABEL: "deploy_dev"

jobs:
  print-labels:
    runs-on: self-hosted
    steps:
      - name: Print Labels
        run: |
          echo ${{ github.event_name }}
          labels="${{ toJson(github.event.pull_request.labels.*.name) }}"
          for label in "$labels"; do
            echo "Label: $label"
          done
          for label in $(echo $labels | jq -r '.[]'); do
            echo "Label: $label"
          done
  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, '${TARGET_PR_LABEL}')) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/development')

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
