name: AVEST CICD DEV

on:
  push:
    branches:
      - development
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
    branches: "development"

env:
  TARGET_PR_LABEL: "deploy_dev"

jobs:
  print-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Print Labels
        run: |
          labels="${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo "Labels: $labels"
          for label in $(echo $labels | jq -r '.[]'); do
            echo "Label: $label"
          done
          if [[ "${{ github.event.pull_request.labels.*.name }}" == *"${TARGET_PR_LABEL}"* ]]; then
            echo "The '${TARGET_PR_LABEL}' label is applied to this pull request."
          else
            echo "The '${TARGET_PR_LABEL}' label is not applied to this pull request."
          fi
  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/development') || 
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, '${TARGET_PR_LABEL}'))

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
